# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_created',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
    ]
